language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

install:
    # Use mirrors to not avoid burdening PyPI
    - pip install --use-mirrors -r requirements.txt
    - pip install -e .

before_script:
    - flake8 .
    - pep257 "--ignore=D100,D101,D102,D103" .

script: py.test .
